// This file is generated by: npm run openapi:types
// Placeholder so TS doesn't complain before the first generation.
// You can delete this once you generate real types.

export type paths = Record<string, unknown>;
